# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainScreenShotsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainScreenShotsWindow(object):
    def setupUi(self, MainScreenShotsWindow):
        MainScreenShotsWindow.setObjectName("MainScreenShotsWindow")
        MainScreenShotsWindow.resize(644, 587)
        self.centralwidget = QtWidgets.QWidget(MainScreenShotsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(80, 20, 181, 41))
        self.label1.setObjectName("label1")
        self.start_screenshots = QtWidgets.QPushButton(self.centralwidget)
        self.start_screenshots.setGeometry(QtCore.QRect(430, 100, 161, 41))
        self.start_screenshots.setObjectName("start_screenshots")
        self.scrLogicListView = QtWidgets.QListView(self.centralwidget)
        self.scrLogicListView.setGeometry(QtCore.QRect(20, 340, 281, 192))
        self.scrLogicListView.setObjectName("scrLogicListView")
        self.printListView = QtWidgets.QListView(self.centralwidget)
        self.printListView.setGeometry(QtCore.QRect(370, 160, 256, 281))
        self.printListView.setObjectName("printListView")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 70, 221, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.dTextBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.dTextBtn.setObjectName("dTextBtn")
        self.gridLayout.addWidget(self.dTextBtn, 0, 0, 1, 1)
        self.printBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.printBtn.setObjectName("printBtn")
        self.gridLayout.addWidget(self.printBtn, 4, 0, 1, 1)
        self.dSwipeBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.dSwipeBtn.setObjectName("dSwipeBtn")
        self.gridLayout.addWidget(self.dSwipeBtn, 2, 0, 1, 1)
        self.sleepBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.sleepBtn.setObjectName("sleepBtn")
        self.gridLayout.addWidget(self.sleepBtn, 3, 0, 1, 1)
        self.dClickBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.dClickBtn.setObjectName("dClickBtn")
        self.gridLayout.addWidget(self.dClickBtn, 1, 0, 1, 1)
        MainScreenShotsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainScreenShotsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainScreenShotsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainScreenShotsWindow)
        self.statusbar.setObjectName("statusbar")
        MainScreenShotsWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainScreenShotsWindow)
        self.actionNew.setObjectName("actionNew")
        self.menu.addAction(self.actionNew)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainScreenShotsWindow)
        QtCore.QMetaObject.connectSlotsByName(MainScreenShotsWindow)

    def retranslateUi(self, MainScreenShotsWindow):
        _translate = QtCore.QCoreApplication.translate
        MainScreenShotsWindow.setWindowTitle(_translate("MainScreenShotsWindow", "截图工具主窗口"))
        self.label1.setText(_translate("MainScreenShotsWindow", "截图动作编辑"))
        self.start_screenshots.setText(_translate("MainScreenShotsWindow", "执行截图"))
        self.dTextBtn.setText(_translate("MainScreenShotsWindow", "查找页面元素"))
        self.printBtn.setText(_translate("MainScreenShotsWindow", "输出"))
        self.dSwipeBtn.setText(_translate("MainScreenShotsWindow", "滑动具体值"))
        self.sleepBtn.setText(_translate("MainScreenShotsWindow", "睡"))
        self.dClickBtn.setText(_translate("MainScreenShotsWindow", "点击指定位置"))
        self.menu.setTitle(_translate("MainScreenShotsWindow", "文件"))
        self.actionNew.setText(_translate("MainScreenShotsWindow", "test"))
