# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setDswipe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 70, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(240, 70, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 180, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(240, 180, 54, 12))
        self.label_4.setObjectName("label_4")
        self.setFxTextEdit = QtWidgets.QTextEdit(Dialog)
        self.setFxTextEdit.setGeometry(QtCore.QRect(100, 50, 104, 71))
        self.setFxTextEdit.setObjectName("setFxTextEdit")
        self.setFyTextEdit = QtWidgets.QTextEdit(Dialog)
        self.setFyTextEdit.setGeometry(QtCore.QRect(270, 50, 104, 71))
        self.setFyTextEdit.setObjectName("setFyTextEdit")
        self.setTxTextEdit = QtWidgets.QTextEdit(Dialog)
        self.setTxTextEdit.setGeometry(QtCore.QRect(100, 160, 104, 71))
        self.setTxTextEdit.setObjectName("setTxTextEdit")
        self.setTyTextEdit = QtWidgets.QTextEdit(Dialog)
        self.setTyTextEdit.setGeometry(QtCore.QRect(280, 160, 104, 71))
        self.setTyTextEdit.setObjectName("setTyTextEdit")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "fx:"))
        self.label_2.setText(_translate("Dialog", "fy:"))
        self.label_3.setText(_translate("Dialog", "tx:"))
        self.label_4.setText(_translate("Dialog", "ty:"))
