# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setDtext.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(433, 329)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 270, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(60, 70, 271, 151))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.DtextEdit = QtWidgets.QTextEdit(self.widget)
        self.DtextEdit.setObjectName("DtextEdit")
        self.verticalLayout_2.addWidget(self.DtextEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dTextClickRadioBtn = QtWidgets.QRadioButton(self.widget)
        self.dTextClickRadioBtn.setObjectName("dTextClickRadioBtn")
        self.verticalLayout.addWidget(self.dTextClickRadioBtn)
        self.dTextExistRadioBtn = QtWidgets.QRadioButton(self.widget)
        self.dTextExistRadioBtn.setObjectName("dTextExistRadioBtn")
        self.verticalLayout.addWidget(self.dTextExistRadioBtn)
        self.dTextNotExistRadioBtn = QtWidgets.QRadioButton(self.widget)
        self.dTextNotExistRadioBtn.setObjectName("dTextNotExistRadioBtn")
        self.verticalLayout.addWidget(self.dTextNotExistRadioBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "想查找的dtext值"))
        self.dTextClickRadioBtn.setText(_translate("Dialog", "点击"))
        self.dTextExistRadioBtn.setText(_translate("Dialog", "存在"))
        self.dTextNotExistRadioBtn.setText(_translate("Dialog", "不存在"))
